### ISSUE TITLE
博客永久链接太长，盖住了侧栏

### ISSUE THREAD

**Issue by tianheg** [Donng/Donng.github.io#1]
![image](https://user-images.githubusercontent.com/52186032/89704210-88aa6400-d984-11ea-9eff-d8ce79aa85a0.png)

[Laravel和Vue的项目搭建:进阶篇](https://donng.github.io/2020/04/laravel%E5%92%8Cvue%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%90%AD%E5%BB%BA%E8%BF%9B%E9%98%B6%E7%AF%87/)

**Comment by donng** [comment]
已修改，感谢指正：   [commit](https://github.com/donng/donng.github.io/commit/908a1705faab735a2a5fbaa8b55b62b184df2146)
